#! /bin/sh

set -e

cd "$(dirname "$0")/.."

sudo apt install -y python3-pip
sudo pip3 install -r requirements.txt

echo "=> Installing fan controller...\n"
sudo cp fancontrol /usr/local/bin/
sudo chmod +x /usr/local/bin/fancontrol

echo "=> Starting fan controller via Systemd...\n"
sudo cp fancontrol.service /lib/systemd/system/fancontrol.service

sudo systemctl daemon-reload
sudo systemctl enable fancontrol.service
sudo systemctl start fancontrol.service

echo "Fan controller installed."
